version: "3"
services:
  frontend:
    image: node:20.0.0-alpine
    container_name: frontend
    working_dir: /home/node
    volumes:
      - ./front:/home/node
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

  #api:
   # image: node:20.0.0-alpine
    #container_name: api
    #working_dir: /app
    #volumes:
     # - ./api:/app
    #ports:
     # - "3000:3000"
    #command: sh -c "npm install && node server.js"
  
  adminer:
    image: adminer:4.8.1
    container_name: adminer
    ports:
      - 8080:8080
    
  postgresdb:
    image: postgres:15.2-alpine
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: ecommerce-user
      POSTGRES_PASSWORD: ChangeMe
    volumes:
      - ./new_db_data:/var/lib/postgresql/data