version: "3"
services:
  frontend:
    image: node:20.0.0-alpine
    container_name: frontend
    working_dir: /home/node
    volumes:
      - ./front:/home/node
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

  api:
    image: node:20.0.0-alpine
    container_name: api
    working_dir: /app
    volumes:
      - ./api:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && node server.js"