name: CI/CD for ecommerce-Challenge Project
on:
  push:
    branches:
      - [ "develop" ]  # Le workflow s'exécutera sur les pushes vers la branche principale
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and Launch Project
      run: docker-compose up -d
        
    - name: Build and Launch Project
      run: docker-compose up -d
        
    - name: Run Tests
      run: npx jest tests/unit/register.test.js  # Vous pouvez exécuter vos tests ici

    - name: Deploy
      run: |
        # Ajoutez les étapes de déploiement si nécessaire

        # Ajoutez les étapes de déploiement si nécessaire
